README.old.md

Removing the old README and getting the dev branch online so we can merge into it!

Removing old readme

---

routes/API/employee.js

Employees routes reflect employees controller

Employees routes

---

routes/API/inventory.js

Inventory routes reflect controller

Inventory routes

---

package-lock.json
package.json
routes/API/employee.js
routes/API/inventory.js
routes/API/menu.js

Menu routes reflect controller. 
Adjusted inventory and employee url routes.

Menu routes; adjusted employee and inventory routes

---

package-lock.json
package.json

added dev modules:
concurrently
nodemon
if-env
also added scripts:
build
start
start:prod
start: dev
client
install

add dev modules nodemon, concurrently, if-env

---

routes/API/time.js

Time routes

---

routes/API/index.js
routes/API/time.js
routes/index.js

Route index complete. Back end server is up and running.

Route index

---

package.json

Server package listed index.js as main, should be server.js

Package.json error

---

client/package-lock.json
client/package.json

It was failing to compile on my end without the react-bootstrap module installed !

Added react-bootstap module. Compiling successfully now

---

routes/API/employee.js
routes/API/index.js
routes/API/inventory.js
routes/API/menu.js
routes/API/time.js
routes/index.js

Routes testing

---

package.json
scripts/inventorySeed.js
scripts/seedDB.js

add seedDB.js
add script command to seed all seed files in script

Seed script

---

scripts/menuSeed.js

Mismatching key for prepareTime

Prep key fix

---

client/src/components/Calendar/index.js

add calendar component

---

client/src/components/Buttons/index.js

Creating dummy buttons

---

client/src/components/Buttons/index.js
client/src/components/Table/index.js

Table which will take in props to render the proper data within  <th>, <tr> and <td>

Creating dummy table

---

client/src/components/DropDownInput/index.js

add drop-down comp

---

client/src/components/FOHOrderDisplay/index.js

FOH Order Display: 
FOH order component exports functions for - 
1. Import container from grid component
2. Order Item card component

add FOHOrderDisplay

---

client/src/utils/employeesAPI.js

I wrote the api/employee routes, but just created the files for the other ones for now

created front end api routes and folder structure

---

client/src/App.js
client/src/components/Buttons/index.js
client/src/pages/Employees/index.js

Forgot to pull <Employees /> out of the App.js in my last PR.

Employees page

---

client/src/App.js
client/src/components/SearchBar/index.js
client/src/components/SearchBar/style.css
client/src/pages/Employees/index.js
client/src/pages/Menu/index.js
client/src/pages/TimeManagement/index.js

Time management page complete.
Also swapped out in line styles for bootstrap classes in Menu and Employees pages! This messed with the width of the search input  (it's kind of small ) but we can play with that later!

Time management page

---

models/ActiveOrder.js
models/ArchivedOrder.js

My thoughts are this: 
Active order:  Will need to receive an order table number. An object of arrays for order item data. Each array containing data on item seat number, item name, and order in time (when order is received -- for logic on front end). It will also need an order in time (for logic on front end to utilize counter)
Let me know if you think I missed anything or we could structure this better 😄

Order active archived models

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Sidebar/index.js
client/src/components/Sidebar/style.css

change the code from original sidebar to make it responsive

sidebar responsive

---

models/Menu.js

remove extra commas in model menu.js

remove extra commas

---

client/src/App.js
client/src/components/Sidebar/index.js
client/src/pages/FOH/index.js

add router/route to App.js file

app routes

---

seeds/seedDB.js

Revise seed func to finish all seeds asynchronously before quitting process.

update seed func

---

models/ActiveOrder.js
models/Time.js
seeds/orderSeed.js
seeds/seedDB.js

add order seed data
correct clockout property in Time model to type DATE
add orderSeed to seedDB.js

Order seed

---

models/ArchivedOrder.js
seeds/archivedOrderSeed.js
seeds/seedDB.js

add archivedOrderSeed.js
bring archived order data to seedDB.js

Archived seed

---

client/src/App.js
client/src/components/DropDownInput/index.js
client/src/components/Sidebar/style.css
client/src/pages/Employees/index.js
client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js

Also added minor styling to remove sidebar disconnected from top of page, and rounded search input edges

Manager inventory add

---

client/src/App.js
client/src/components/Sidebar/index.js
client/src/pages/TimeManagement/index.js

Time clock component back in manager portal

Re render timeclock

---

client/src/pages/Employees/index.js
client/src/utils/employeesAPI.js

Employees populate 

---

client/src/components/Buttons/index.js
client/src/pages/Inventory/index.js
package-lock.json
package.json

Inventory add item functionality complete. Form validation complete with messages notifying user of success or error (empty input fields). May need better message styling at some point

Inventory add item

---

controllers/activeOrderController.js
controllers/archivedOrderController.js
routes/API/activeOrder.js
routes/API/archivedOrder.js
routes/API/employee.js
routes/API/index.js
routes/API/inventory.js
routes/API/menu.js
routes/API/time.js
routes/index.js

add active order routes
add archived order routes
'use strict' for all
use back tick for all
remove arrow-parens

Routes update

---

client/src/pages/Inventory/index.js

Inventory page fields validate for numbers as well (previously only validated for empty input)

Validating for numbers

---

client/src/App.js
client/src/components/EmployeeModal/index.js
client/src/components/Sidebar/index.js
client/src/pages/Employees2.js
client/src/pages/Employees2/index.js

to avoid conflict, i added another employee page that uses modal to add new employees.
add a new version of employee page
use modal to add new employee

Employee modal

---

client/src/components/NumPad/index.js

In the middle of working on auth I found some improvements!

Improved functionality of numpad

---

client/src/components/Buttons/index.js
client/src/components/DropDownInput/index.js
client/src/components/SearchBar/index.js
client/src/pages/Employees/index.js
client/src/pages/Employees2/index.js
client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js

Just some random little style things I thought would be good to clean up before we show them today -- I can revert anything back also !

Random little things

---

client/src/pages/TimeManagement/index.js
models/Time.js
seeds/shiftSeed.js

Added default null to time model for clock out. Added ternary expression to render client on the clock, or clock out time if value !== null

Adjustments on clock out model, seed, rendering

---

client/src/pages/Inventory/index.js

New modal good to go for add to inventory

Reusable modal inventory

---

client/src/pages/Inventory/index.js

Inventory modal title

---

client/src/components/DataTable/index.js
client/src/pages/Employees2/index.js

add 'hideEdit' prop name to DataTable. This is a boolean property. If true, the checkboxes are hidden. If false, the checkboxes are shown to each row in DataTable.

add checkboxes to table rows

---

client/src/pages/Inventory/index.js

I commented out my view and delete functionality to make room for check boxes, but also to preserve them for now in case we want them back or need to reference them ! If not, I will remove !
That big red chunk is beautiful 👍

Dynamic table in inventory

---

client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js

Menu updated to new modal and table

Menu add modal

---

client/src/pages/TimeManagement/index.js

Shifts has new table component and edit bar

Shifts has edit bar and new text box

---

client/src/pages/Employees2/index.js
client/src/utils/employeesAPI.js
controllers/employeesController.js
routes/API/employee.js

add deleteMany to employee page
add the route
add the api
add viewEmployee() after delete

Employee delete many

---

client/src/components/EditBar/index.js
client/src/pages/Employees/index.js

change modal input depending on number of employees selected to edit.

change modal input in edit

---

seeds/employeeSeed.js

add more dummy seed data for employees.
this also confirms that data model takes in string value

add more employee seed data

---

client/src/components/Buttons/index.js
client/src/components/Calendar/index.js
client/src/components/DataTable/index.js
client/src/pages/Inventory/index.js
client/src/pages/TimeManagement/index.js

Shifts are able to be filtered

Shift search filter

---

client/src/components/InputModal/index.js
client/src/pages/Employees/index.js
client/src/utils/employeesAPI.js
controllers/employeesController.js
routes/API/employee.js

Add updateMany to employee api, router, model
add update many function to employee page

Employee state

---

client/src/pages/Menu/index.js
client/src/utils/menuAPI.js
controllers/menuController.js
routes/API/menu.js

Menu up to date with new add, update, and delete logic style

Menu update delete

---

client/src/pages/Inventory/index.js
client/src/utils/inventoryAPI.js

Inventory update

---

client/src/pages/TimeManagement/index.js
client/src/utils/timeAPI.js
controllers/timeController.js
routes/API/time.js

The back end routes, controller, and front end api calls are also fleshed out so you should be good to go on writing functionality for add, update and delete

Shifts update delete

---

.gitignore
package.json
server.js

remove magic number from server.js

---

client/src/pages/Employees/index.js
client/src/pages/Menu/index.js
models/Menu.js
seeds/menuSeed.js

revise menu model, remove itemCount, change price from Number to String.
change menu seed data price from number to string
remove unnecessary parens

revise menu page and model

---

client/src/pages/Employees/index.js
client/src/pages/Menu/index.js

fix the delete button bug, where it doesn't go away after delete.

fix edit button bug

---

client/src/components/EditBar/index.js
client/src/pages/Employees/index.js
client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js
client/src/pages/TimeManagement/index.js

add hideAddButton prop to EditBar component.
It'll hide/show Add button.

add hideAddButton props to EditBar

---

models/Time.js
seeds/seedDB.js
seeds/shiftSeed.js

change time model clockIn and clockOut type to String
added clockout seed data.

update time model and seeds

---

client/package-lock.json
client/package.json
client/src/pages/Home/index.js

Login date

---

client/src/pages/Employees/index.js
client/src/pages/FOH/index.js
client/src/utils/inventoryAPI.js
controllers/inventoryController.js
models/Menu.js
routes/API/inventory.js
seeds/inventorySeed.js
seeds/menuSeed.js

Decrement working on item sold. Currently decrements at 1. Will see if we can make decrement dynamic if that's something we want to pursue?

Inventory decrement 2

---

client/src/pages/Inventory/index.js
controllers/inventoryController.js
routes/API/inventory.js

Update inventory routes and controller

update inventory routes and controller

---

client/src/pages/Home/index.js
client/src/pages/Home/style.css

add styling to greeting for home page

home page greeting styling

---

client/src/pages/TimeManagement/index.js
client/src/utils/timeAPI.js
controllers/timeController.js

Shift delete

---

controllers/inventoryController.js

The inventory controller that was just merged was not completely closed

Inventory call not closed

---

client/src/components/FloorPlan/index.js

Fixed equality issues in floor plans to get rid of console warnings. Added h2 content because it was mad that element was empty as well.

Working through the console warnings

---

client/src/pages/BOH/index.js

Fixed a conflict that was breaking functionality

Removed icon due to conflicts

---

client/src/pages/Employees/index.js
client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js
client/src/pages/TimeManagement/index.js
client/src/utils/employeesAPI.js
client/src/utils/menuAPI.js

remove extra parens
remove comments
remove unused api calls in util

Remove extra parens

---

seeds/menuSeed.js

Added more bev options to menu seed

Added more bev options to menu seed

---

client/src/components/Calendar/index.js
client/src/components/Calendar/style.css
client/src/components/FloorPlan/style.css
client/src/components/SearchBar/style.css
client/src/pages/Menu/style.css

Various little changes. Added weird shape to shifts calendar. Let me know what you think I can't tell if it's weird or cool in a weird way so I can remove if we don't like

Small font adjust

---

client/src/pages/TimeManagement/index.js
seeds/shiftSeed.js

Shifts filter fixed. Fixed seed with / instead of - from earlier testing of filter

Fix shifts filter

---

client/src/pages/FOH/index.js
client/src/pages/Home/index.js
client/src/pages/Menu/style.css

- modal instead of alerts
- refreshes on submit!

tiny stuff

---

server.js

added __dirname

---

client/src/App.js

Browser -> Hash

---

README.md
client/src/pages/BOH/index.js
client/src/pages/Employees/index.js
client/src/pages/FOH/style.css
client/src/pages/Inventory/index.js
client/src/pages/Menu/index.js
client/src/pages/TimeManagement/index.js

Update dev branch to same commits as master.

Update dev branch
